# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_channel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QlfState',
        ),
    ]
