version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qlfuser
      - POSTGRES_USER=userqlf
      - POSTGRES_DB=dbqlf
    ports:
      - "5432"
  qlf:
    build: .
    environment:
      - QLF_API_URL=http://localhost:8000/dashboard/api
      - QLF_BASE_URL=http://localhost:8000
      - QLF_HOSTNAME=localhost
      - QLF_ROOT=/app/
      - DESI_SPECTRO_DATA=/app/spectro/data
      - DESI_SPECTRO_REDUX=/app/spectro/redux
      - QL_SPEC_DATA=/app/spectro/data
      - QL_SPEC_REDUX=/app/spectro/redux
      - OMP_NUM_THREADS=1 # This avoids unwanted concurrency during BoxcarExtract
      - POSTGRES_PASSWORD=qlfuser
      - POSTGRES_USER=userqlf
      - POSTGRES_DB=dbqlf
    volumes:
      - .:/app
    restart: always
    working_dir: /app/
    command: ./run.sh
    ports:
      - "8000:8000"
      - "5006:5006"
      - "56005:56005"
    depends_on:
      - redis
      - db
  redis:
    image: redis
    ports:
      - "6379"
