# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccd',
            name='prop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ccd',
            name='prop2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='prop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='prop2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fiber',
            name='prop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fiber',
            name='prop2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='prop1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='prop2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='sn_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spectrograph',
            name='prop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spectrograph',
            name='prop2',
            field=models.FloatField(default=0.0),
        ),
    ]
