# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160120_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrograph',
            name='exposure_id',
        ),
    ]
