# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QlfState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daemon_status', models.BooleanField(default=False)),
                ('upstream_status', models.BooleanField(default=False)),
            ],
        ),
    ]
