# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 20:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera', models.CharField(help_text='Camera ID', max_length=2, primary_key=True, serialize=False)),
                ('spectrograph', models.CharField(help_text='Spectrograph ID', max_length=1)),
                ('arm', models.CharField(help_text='Arm ID', max_length=1)),
                ('qa_tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON structure with the QA tests results', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(help_text='Configuration used.')),
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Datetime when the configuration was created')),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('exposure_id', models.IntegerField(help_text='Exposure number', primary_key=True, serialize=False)),
                ('telra', models.FloatField(blank=True, help_text='Central RA of the exposure', null=True)),
                ('teldec', models.FloatField(blank=True, help_text='Central Dec of the exposure', null=True)),
                ('tile', models.IntegerField(blank=True, help_text='Tile ID', null=True)),
                ('dateobs', models.DateTimeField(blank=True, help_text='Date of observation', null=True)),
                ('flavor', models.CharField(default='Object', help_text='Type of observation', max_length=45)),
                ('night', models.CharField(blank=True, db_index=True, help_text='Night ID', max_length=45)),
                ('airmass', models.FloatField(blank=True, help_text='Airmass', null=True)),
                ('exptime', models.FloatField(blank=True, help_text='Exposure time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quick Look', help_text='Name of the job.', max_length=45)),
                ('start', models.DateTimeField(auto_now=True, help_text='Datetime when the job was started')),
                ('end', models.DateTimeField(blank=True, help_text='Datetime when the job was finished.', null=True)),
                ('status', models.SmallIntegerField(default=2, help_text='Job status, 0=OK, 1=Failed, 2=Running')),
                ('version', models.CharField(help_text='Version of the pipeline', max_length=16, null=True)),
                ('logname', models.CharField(help_text='Name of the log file.', max_length=45, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_jobs', to='dashboard.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(help_text='Name of the pipeline.', max_length=60)),
                ('process_dir', models.CharField(help_text='Path to process', max_length=145)),
                ('version', models.CharField(help_text='Path to process', max_length=45)),
                ('start', models.DateTimeField(auto_now=True, help_text='Datetime when the process was started')),
                ('end', models.DateTimeField(blank=True, help_text='Datetime when the process was finished.', null=True)),
                ('status', models.SmallIntegerField(default=0, help_text='Process status, 0=OK, 1=Failed')),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_exposure', to='dashboard.Exposure')),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='QA name', max_length=45)),
                ('description', models.TextField(help_text='QA Description')),
                ('paname', models.CharField(help_text='Associate PA name', max_length=45)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON structure with the QA result')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON structure with the QA tests')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_qas', to='dashboard.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_jobs', to='dashboard.Process'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_process', to='dashboard.Process'),
        ),
    ]
