# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='qa_tests',
        ),
    ]
