# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_camera_qa_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='process',
        ),
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='QLF', help_text='Name of the configuration.', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='process',
            name='configuration',
            field=models.ForeignKey(default='ql', on_delete=django.db.models.deletion.CASCADE, related_name='process_configuration', to='dashboard.Configuration'),
            preserve_default=False,
        ),
    ]
