# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 12:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180507_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Configuration used.'),
        ),
    ]
