# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 13:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180509_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='qa_tests',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='QA tests summary.'),
        ),
    ]
