# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_process_qa_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='program',
            field=models.CharField(blank=True, help_text='Program', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='dateobs',
            field=models.DateTimeField(help_text='Date of observation'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='night',
            field=models.CharField(db_index=True, help_text='Night ID', max_length=45),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='teldec',
            field=models.FloatField(help_text='Central Dec of the exposure'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='telra',
            field=models.FloatField(help_text='Central RA of the exposure'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='tile',
            field=models.IntegerField(help_text='Tile ID'),
        ),
    ]
