# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 20:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20180607_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_comments', to='dashboard.Process')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
