# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 14:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_processcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON structure with the QA result', null=True),
        ),
    ]
