# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logname',
            field=models.CharField(help_text='Name of the log file.', max_length=65, null=True),
        ),
    ]
