# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 17:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180727_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibermap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_obs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('dec_obs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('fiber', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('objtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibermap_exposure', to='dashboard.Exposure')),
            ],
        ),
        migrations.RemoveField(
            model_name='qa',
            name='job',
        ),
        migrations.DeleteModel(
            name='QA',
        ),
    ]
