# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180921_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibermap',
            old_name='dec_obs',
            new_name='fiber_dec',
        ),
        migrations.RenameField(
            model_name='fibermap',
            old_name='ra_obs',
            new_name='fiber_ra',
        ),
    ]
