# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 18:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20181002_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfternoonJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quick Look', help_text='Name of the job.', max_length=45)),
                ('start', models.DateTimeField(auto_now=True, help_text='Datetime when the job was started')),
                ('end', models.DateTimeField(blank=True, help_text='Datetime when the job was finished.', null=True)),
                ('status', models.SmallIntegerField(default=2, help_text='Job status, 0=OK, 1=Failed, 2=Running')),
                ('version', models.CharField(help_text='Version of the pipeline', max_length=16, null=True)),
                ('logname', models.CharField(help_text='Name of the log file.', max_length=65, null=True)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON structure with the QA result', null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_afternoon_jobs', to='dashboard.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='AfternoonProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(help_text='Name of the pipeline.', max_length=60)),
                ('process_dir', models.CharField(help_text='Path to process', max_length=145)),
                ('version', models.CharField(help_text='Path to process', max_length=45)),
                ('start', models.DateTimeField(auto_now=True, help_text='Datetime when the process was started')),
                ('end', models.DateTimeField(blank=True, help_text='Datetime when the process was finished.', null=True)),
                ('status', models.SmallIntegerField(default=0, help_text='Process status, 0=OK, 1=Failed')),
                ('qa_tests', django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='QA tests summary.')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_process_configuration', to='dashboard.Configuration')),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_process_exposure', to='dashboard.Exposure')),
            ],
        ),
        migrations.AddField(
            model_name='afternoonjob',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_process_afternoon_jobs', to='dashboard.AfternoonProcess'),
        ),
    ]
