# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCD',
            fields=[
                ('ccd_id', models.AutoField(primary_key=True, serialize=False)),
                ('arm', models.CharField(max_length=200)),
                ('prop1', models.IntegerField(default=0)),
                ('prop2', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('exposure_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop1', models.IntegerField(default=0)),
                ('prop2', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('fiber_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop1', models.IntegerField(default=0)),
                ('prop2', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('spectra_id', models.AutoField(primary_key=True, serialize=False)),
                ('counts', models.IntegerField(default=0)),
                ('sn_ratio', models.FloatField(default=0.0)),
                ('prop1', models.FloatField(default=0.0)),
                ('prop2', models.FloatField(default=0.0)),
                ('ccd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.CCD')),
            ],
        ),
        migrations.CreateModel(
            name='Spectrograph',
            fields=[
                ('spectrograph_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop1', models.IntegerField(default=0)),
                ('prop2', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='fiber',
            name='spectrograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Spectrograph'),
        ),
        migrations.AddField(
            model_name='ccd',
            name='exposure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Exposure'),
        ),
        migrations.AddField(
            model_name='ccd',
            name='spectrograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Spectrograph'),
        ),
    ]
